/*$(document).ready(function(){
    $("#img1").click(function(){
      $(".im1").toggle(1000);
    });
  });*/
  $(document).ready(function(){
    $("#img2").click(function(){
        $(".im2").toggle(500);
    });
  });
  $(document).ready(function(){
    $("#img3").click(function(){
        $(".im3").toggle(500);
    });
  });
  $(document).ready(function(){
    $("#img4").click(function(){
        $(".im4").toggle(500);
    });
  });
  $(document).ready(function(){
    $("#img5").click(function(){
        $(".im5").toggle(500);
    });
  });
  $(document).ready(function(){
    $("#img6").click(function(){
        $(".im6").toggle(500);
    });
  });
  $(document).ready(function(){
    $("#img1").click(function(){
        $(".im1").toggle(500);
    });
  });